- name: Install nodejs
  sudo: yes
  apt: pkg=nodejs state=latest

- name: Install npm
  sudo: yes
  apt: pkg=npm state=latest

- name: Install packages
  npm: name={{ item }} global=yes state=present
  with_items: nodejs_packages